#!/usr/bin/env python

from distutils.core import setup, Extension

graph_module = Extension(
   '_Graph',
   sources=['Graph_wrap.cxx', 'Graph.cpp'], # Graph_wrap.cpp is going to be generated by swig
)

setup (
	name        = 'Graph',
	version     = '0.1',
	author      = "",
	description = "Graph swig",
	ext_modules = [graph_module],
	py_modules  = ["Graph"], # name of module that we're going import
)
